### ISSUE TITLE
Get Shipment webhook does not automatically

### ISSUE THREAD

**Issue by saravananNV** [wombat/fifthgear_integration#2]
Hello Developers,

  I am saran N.V a RoR developer from india. i am integrating fifth gear connection  with our wombat account.we successfully placed an order to fifth gear and created shipments webhook to receive shipments.but we did not get any response from fifth gear.is it there any problem on our side we set frequency to five minutes to call get shipments.

**Comment by phstc** [comment]
Hi @saravananNV 

Could you send a message to support@spreecommerce.com with your flow link/URL in Wombat?

Thanks

**Comment by saravananNV** [comment]
hi @phstc  

  K..thanks for your comments.
